server:
  port: 8080
spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/my_study?characterEncoding=utf-8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
    slave:
      jdbc-url: jdbc:mysql://localhost:3306/my_study_slave?characterEncoding=utf-8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root