server:
  port: 8080
spring:
  datasource:
    master:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/my_study?charset=utf-8&serverTimezone=GMT%2B8
    slave:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/my_study_slave?charset=utf-8&serverTimezone=GMT%2B8