server:
  port: 8080
spring:
  datasource:
    default:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/my_study?characterEncoding=utf-8
      username: root
      password: root